server:
  port: 8761

spring:
  application:
    name: SERVICE-A
  datasource:
    druid:
  cloud:
    loadbalancer:
      retry:
        enabled: false

      # WebStatFilter 用于采集 web-jdbc 关联监控的数据。
      web-stat-filter:
        # 是否开启 WebStatFilter 默认是 true
        enabled: true
        # 需要拦截的 url
        url-pattern: /*
        # 排除静态资源的请求
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

      # Druid 内置提供了一个 StatViewServlet 用于展示 Druid 的统计信息。
      stat-view-servlet:
        #是否启用 StatViewServlet 默认值 true
        enabled: true
        # 需要拦截的 url
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: druid
        login-password: druid
nacos:
  config:
    #nacos地址
    server-addr: 129.211.71.185:8848
    #命名空间
    namespace: 331a4edf-0d3b-48fc-892a-2370fc2bf0fb
    #配置文件类型，目前只支持yaml,yml,properties,目前不需要了
    file-extension: yaml
    #默认提供者，目前不需要了
    prefix: SERVICE-A
rocketmq:
  # 生产者配置
  producer:
    #该应用是否启用生产者
    isOnOff: on
    # 发送同一类消息的设置为同一个group，保证唯一
    groupName: chengroup
    # 发送同一类消息的设置为同一个group，保证唯一
    groupName2: chengroup2
    # 服务地址
    namesrvAddr: 129.211.71.185:9876
    # 消息最大长度 默认1024*4(4M)
    maxMessageSize: 4096
    # 发送消息超时时间,默认3000
    sendMsgTimeout: 3000
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2
  # 消费者配置
  consumer:
    #该应用是否启用消费者
    isOnOff: on
    # 官方建议：确保同一组中的每个消费者订阅相同的主题。
    groupName: chengroup
    # 服务地址
    namesrvAddr: 129.211.71.185:9876
    # 接收该 Topic 下所有 Tag
    topics: mytopic~*;mytopic2~*;
    consumeThreadMin: 20
    consumeThreadMax: 64
    # 设置一次消费消息的条数，默认为1条
    consumeMessageBatchMaxSize: 1
# 配置 Group  Topic  Tag
rocket:
  #发送消息group不用填写
  group: chengroup
  group2: chengroup2
  topic: mytopic
  topic2: mytopic2
  tag: rocketTag
  tag2: rocketTag2

eureka:
  client:
    serviceUrl:
      defaultZone: http://134.175.217.13:8761/eureka/


ribbon:
  # 同一实例最大重试次数，不包括首次调用。默认值为0
  MaxAutoRetries: 0
  # 同一个微服务其他实例的最大重试次数，不包括第一次调用的实例。默认值为1
  MaxAutoRetriesNextServer: 0
  # 是否所有操作（GET、POST等）都允许重试。默认值为false
  OkToRetryOnAllOperations: false